server:
  port : 8082
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
spring:
  application:
     name: encryptor
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        encryption-queue:
          destination: encryption
          contentType: application/json
        upload-queue:
          destination: upload
          contentType: application/json
