server:
  port : 8081
certificate:
  path: C:\\OpenSSL\\bin
  pass: secure
keystore-type: PKCS12 
keystore-password: secure 
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
spring:
  application:
     name: signer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        signature-queue:
          destination: signature
          contentType: application/json
        encryption-queue:
          destination: encryption
          contentType: application/json