server:
  port : 8083
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
spring:
  application:
     name: uploader
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        cleanup-queue:
          destination: cleanup
          contentType: application/json
        upload-queue:
          destination: upload
          contentType: application/json
